# =============================================================================
# ACME Commander 配置文件示例
# =============================================================================
# 版本: 0.1.2
#
# 配置文件支持以下功能:
# - 多语言国际化支持 (zh-CN, ja-JP, en-US)
# - 多 ACME 提供商支持 (Let's Encrypt, ZeroSSL, FreeSSL.cn)
# - 多 DNS 提供商支持 (Cloudflare, 阿里云 DNS, DNSPod)
# - 灵活的证书管理策略
# =============================================================================
#
# 使用说明：
# 1. 复制此文件为 config.toml
# 2. 根据您的实际需求修改配置
# 3. 填写您的敏感凭证信息（API Token、邮箱等）
# 4. 此文件包含敏感信息，请勿提交到版本控制系统
#
# 配置优先级（从高到低）：
# - 命令行参数 > 环境变量 > 配置文件 > 默认值
# =============================================================================

# =============================================================================
# 账户配置
# =============================================================================
[account]
# 注册ACME账户的邮箱地址（必需）
# Let's Encrypt会通过此邮箱发送证书过期通知
email = "your-email@example.com"

# 账户私钥文件路径（可选，如果不存在会自动生成）
key_file = "./account.key"

# 是否同意ACME服务条款（必需）
# 设置为 true 表示您同意ACME提供商的服务条款
terms_of_service_agreed = true

# 联系信息列表（可选，通常只使用邮箱即可）
# 格式：["mailto:your-email@example.com"]
contacts = []

# =============================================================================
# 证书配置
# =============================================================================
[certificate]
# 证书私钥文件路径（如果不存在会自动生成）
key_file = "./certificate.key"

# 单独证书文件路径（只包含域名证书，不包含中间证书）
cert_file = "./certificate.pem"

# 中间证书链文件路径（只包含中间证书）
chain_file = "./chain.pem"

# 完整证书链文件路径（域名证书 + 中间证书，推荐用于Web服务器）
fullchain_file = "./fullchain.pem"

# CSR文件路径（可选，如果不存在或注释掉则会自动生成）
# 如果指定了路径且文件存在：使用现有的CSR文件
# 如果指定了路径但文件不存在：生成CSR并保存到文件
# 如果注释掉或为空：在内存中生成CSR，不保存文件
# csr_file = "./certificate.csr"

# 申请证书的域名列表（必需）
# 可以包含主域名和多个子域名
domains = ["example.com", "www.example.com", "api.example.com"]

# =============================================================================
# ACME 服务器配置
# =============================================================================
[acme]
# ACME 提供商（必需）
# 可选值：
# - "letsencrypt": Let's Encrypt（推荐，完全免费）
# - "zerossl": ZeroSSL（开发中）
# - "freessl": FreeSSL.cn（计划中）
provider = "letsencrypt"

# 运行环境（必需）
# 可选值：
# - "sandbox": 沙盒环境（测试用，无速率限制）
# - "production": 生产环境（正式环境，有速率限制）
environment = "sandbox"

# 是否同意ACME服务条款（必需）
terms_of_service_agreed = true

# 请求超时时间（秒，默认30）
timeout_seconds = 30

# 失败重试次数（默认3）
retry_count = 3

# 重试间隔时间（秒，默认5）
retry_interval = 5

# 用户代理字符串（默认自动生成）
# 用于标识您的ACME客户端，不建议修改
user_agent = "acme-commander/0.1.1"

# =============================================================================
# DNS 验证配置
# =============================================================================
[dns]
# DNS 提供商（必需）
# 可选值：
# - "cloudflare": Cloudflare DNS（已实现）
# - "aliyun": 阿里云 DNS（计划中）
# - "dnspod": DNSPod（计划中）
provider = "cloudflare"

# DNS 记录传播超时时间（秒，默认600）
# 等待DNS记录在全球DNS服务器上传播的最长时间
propagation_timeout = 600

# DNS 传播检查间隔（秒，默认30）
# 每隔多少秒检查一次DNS记录是否已成功传播
propagation_interval = 30

# DNS 服务器列表（用于检查DNS传播）
# 用于验证DNS记录是否已正确传播的DNS服务器
dns_servers = ["8.8.8.8", "1.1.1.1"]

# DNS 记录默认TTL（秒，默认300）
# 新添加的DNS记录的生存时间
default_ttl = 300

# =============================================================================
# Cloudflare DNS 配置
# =============================================================================
[dns.cloudflare]
# Cloudflare API Token（必需）
# 获取方式：
# 1. 登录 Cloudflare 控制台
# 2. 进入 "我的个人资料" → "API 令牌"
# 3. 点击 "查看令牌" → "创建令牌"
# 4. 选择 "编辑区域 DNS" 模板
# 5. 选择要管理的域名，设置权限
# 6. 生成的令牌具有 Zone:DNS:Edit 权限即可
api_token = ""

# Cloudflare API 基础URL（通常无需修改）
api_base_url = "https://api.cloudflare.com/client/v4"

# Cloudflare API 请求超时时间（秒，默认30）
timeout_seconds = 30

# =============================================================================
# ZeroSSL 配置（可选，暂未实现）
# =============================================================================
[zerossl]
# ZeroSSL API Key（如果使用ZeroSSL作为ACME提供商）
api_key = ""

# ZeroSSL API 基础URL（通常无需修改）
api_base_url = "https://api.zerossl.com"

# ZeroSSL API 请求超时时间（秒，默认30）
timeout_seconds = 30

# =============================================================================
# FreeSSL.cn 配置（计划中）
# =============================================================================
[freessl]
# FreeSSL.cn API 密钥（如果使用FreeSSL.cn作为ACME提供商）
api_key = ""

# FreeSSL.cn API 基础URL（通常无需修改）
api_base_url = "https://api.freessl.cn"

# FreeSSL.cn API 请求超时时间（秒，默认30）
timeout_seconds = 30

# =============================================================================
# 阿里云 DNS 配置（计划中）
# =============================================================================
[dns.aliyun]
# 阿里云 AccessKey ID
access_key_id = ""

# 阿里云 AccessKey Secret
access_key_secret = ""

# 阿里云区域 ID
region_id = "cn-hangzhou"

# 阿里云 API 基础URL（通常无需修改）
api_base_url = "https://alidns.aliyuncs.com"

# 阿里云 API 请求超时时间（秒，默认30）
timeout_seconds = 30

# =============================================================================
# DNSPod 配置（计划中）
# =============================================================================
[dns.dnspod]
# DNSPod API Token
api_token = ""

# DNSPod API 基础URL（通常无需修改）
api_base_url = "https://dnsapi.cn"

# DNSPod API 请求超时时间（秒，默认30）
timeout_seconds = 30

# =============================================================================
# 国际化配置
# =============================================================================
[i18n]
# 语言设置（可选，默认自动检测系统语言）
# 可选值：auto, zh-CN, ja-JP, en-US
language = "auto"

# 是否启用语言自动检测
auto_detect = true

# =============================================================================
# 日志配置
# =============================================================================
[logging]
# 日志级别（默认info）
# 可选值：error, warn, info, debug, trace
level = "info"

# 日志输出配置（支持多个输出）
# output_type: 输出类型（console/file）
# format: 日志格式（json/text）
outputs = [
    { output_type = "console", format = "json" },
    # { output_type = "file", format = "text" }
]

# 是否使用颜色（仅在console输出时有效）
colored = true

# 时间戳格式
# 常用格式："%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M:%S.%3f"
timestamp_format = "%Y-%m-%d %H:%M:%S"

# =============================================================================
# 环境变量配置（可选）
# =============================================================================
# 您也可以通过环境变量覆盖配置文件中的设置：
#
# ACME_PROVIDER: letsencrypt/zerossl/freessl
# ACME_ENVIRONMENT: sandbox/production
# ACME_ACCOUNT_EMAIL: your-email@example.com
# DNS_PROVIDER: cloudflare/aliyun/dnspod
# CLOUDFLARE_API_TOKEN: your-api-token
# ALIYUN_ACCESS_KEY_ID: your-access-key-id
# ALIYUN_ACCESS_KEY_SECRET: your-access-key-secret
# DNSPOD_API_TOKEN: your-api-token
# I18N_LANGUAGE: auto/zh-CN/ja-JP/en-US
#
# 环境变量的优先级高于配置文件
# =============================================================================


